version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /enrica/app/node_modules
      - .:/enrica/app
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /enrica/app/node_modules
      - .:/enrica/app
    command: ["npm", "run", "test"]

